### ISSUE TITLE
GraphQL support broken (once again)

### ISSUE THREAD

**Issue by levrik** [hoppscotch/hoppscotch-extension#12]
**Describe the bug**

GraphQL requests work in general but I can't see the response from server. Neither if the request was successful or not (means contains `errors` or not).
Instead I'm just getting `SyntaxError: Unexpected token  in JSON at position 85. Check console for details.`.
With a different position depending on the actual JSON returned by server.
I think the unexpected token seems to be a space?
Sadly I can't check the response since this is routed through the extension. Some debug mode for the extension would be great, that it logs request/response pairs or similar. I can file another issue for this if it sounds good to you.

**To Reproduce**
1. Go to GraphQL section
2. Get the schema (works fine)
3. Enter some query or mutation
4. Send it and see this error described above.

**Expected behavior**
Returned JSON to be shown

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 85

**Additional context**

It's starting to get kinda "funny". Every time I'm using this application, something else is broken. Most of the time around GraphQL support, sometimes also just in general. I really like the look and feel of this application and it really makes me sad that every time I want to use some fundamental functionality is broken.

**Comment by AndrewBastin** [comment]
Yup, this is known :sweat_smile: . I just couldn't get to the bottom of the issue yet, because it is a bit random.

Trying to work on a fix for that soon. I am busy working on the Teams system. Closing this issue as it is basically same underlying issue as #11
