### ISSUE TITLE
How to build extension for Chrome browser?

### ISSUE THREAD

**Issue by tagnja** [hoppscotch/hoppscotch-extension#13]

**Comment by liyasthomas** [comment]
Refer [Building & Experimentation](https://github.com/hoppscotch/hoppscotch-extension#building--experimentation) section in README.

- Step 1: [Setup a local copy of Hoppscotch repo](https://github.com/hoppscotch/hoppscotch#local-development-environment)
- Step 2: [Clone the extension repo](https://github.com/hoppscotch/hoppscotch-extension)
- Step 3: Edit `manifest.json` in root of extension repo to the following:
```
  "content_scripts": [
    {
      "matches": [
        "*://*/*",
        "https://hoppscotch.io/",
        "https://hoppscotch.io/*",
        "https://hoppscotch.netlify.com/*",
        "https://hoppscotch.netlify.com/"
      ],
      "js": [ "contentScript.js" ]
    }
  ],
```
- Step 4: Run `npm install`
- Step 5: Run `npm run build` to generate the dist folder
- Step 6: Install the extension using your browser's install options (a quick google search will yield the methods).
