### ISSUE TITLE
Unable to see Requests in DevTools when using extension

### ISSUE THREAD

**Issue by seanaye** [hoppscotch/hoppscotch-extension#173]
When using the hoppscotch proxy requests which are sent are shown in the Chrome DevTools console.

When using the browser extension the requests never appear. This makes it much harder to understand the content of the requests being sent/received.

**Comment by AndrewBastin** [comment]
Yeah, well when you send a request through the extension it is routed through the extension internally and not through the app itself. If you want to see the request contents from DevTools, you can follow these steps in Chromium based browsers:

1. Open `chrome://extensions` page (or its alternatives for your browser)
2. Turn on Developer Mode toggle.
3. In the entry for the Hoppscotch Browser Extension, click on the `Inspect views: Background Page` link
4. A new DevTools Window should be open, that is the DevTools for the extension which you can use to see request contents.
