### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by pingapi** [hoppscotch/hoppscotch-extension#177]
Manifest version 2 is deprecated, and support will be removed in June 2023. At that time, Manifest V2 extensions no longer function in Chrome even with the use of enterprise policy.

**Comment by Abjcodes** [comment]
I can migrate it into v3, if the issue is still open.

**Comment by AndrewBastin** [comment]
@Abjcodes this is already implemented with #186.
We were waiting for the updated timeline from Chrome to close in to merge this in.
We will be merging and releasing this sometime this month.
