### ISSUE TITLE
[bug]: TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Request with GET/HEAD method cannot have body.

### ISSUE THREAD

**Issue by udivankin** [hoppscotch/hoppscotch-extension#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

GET/HEAD requests stopped working after a recent Chrome update.

### Steps to reproduce

1. Install Chrome 119 w/Browser Extension v0.28
2. Create GET or HEAD request to any valid host (or use one that previously succeeded)
3. No response with a suggestion to choose a proxy, just like no extension installed.
4. Open dev console
<img width="951" alt="Screenshot 2023-12-19 at 23 10 58" src="https://github.com/hoppscotch/hoppscotch/assets/1522846/5fd2ca78-5568-4a7e-8472-25ddd3c76d5c">

Export to curl/fetch shows the body param (which is empty) - may be the cause.

### Environment

Production

### Version

Local

**Comment by AndrewBastin** [comment]
Yes, I can reproduce this, for the time being, a fix for it is to set the Body Content-Type to None on your requests having GET/HEAD to prevent the app from sending a body to the extension.

I will push a patch to the extension to ignore the body field on GET/HEAD methods.

**Comment by sats268842** [comment]
I tried setting the Body Content-Type to None, but it kept throwing new errors.

![image](https://github.com/hoppscotch/hoppscotch-extension/assets/42093035/1fbc316d-0e1f-456a-bfff-6e151dc5a73a)

**Comment by sats268842** [comment]
Thank you, @AndrewBastin  It's working now.

**Comment by sats268842** [comment]
![image](https://github.com/hoppscotch/hoppscotch-extension/assets/42093035/476f36ce-2b64-4a87-9d74-9a6493b2dc02)
It showing error like this

**Comment by AndrewBastin** [comment]
@sats268842 can you open this as a new issue on this repo ?

cc: @amk-dev

**Comment by AndrewBastin** [comment]
I have issued a new release 0.29 which will ignore the body on `GET/HEAD` method calls. It should be available on both the browsers in a couple of hours.
