### ISSUE TITLE
[bug]: Chrome extension loses origin list after Chrome restart or backend upgrade

### ISSUE THREAD

**Issue by tomerr-ma** [hoppscotch/hoppscotch-extension#269]
We have noticed that sometimes (seems to be correlated with version upgrades of the hoppscotch backend version), we lost the Hoppscotch URL in the Chrome extension.

**Comment by tomerr-ma** [comment]
We Also see it happens also in Chrome restart and not necessarily when upgrading version which is more severe.

**Comment by tomerr-ma** [comment]
@liyasthomas @AndrewBastin the bug seems to be triggered when Chrome version update occurs.

Seems like `chrome.runtime.onInstalled.addListener(()` in src/index.js, Line:358 is using this function which according to the docs is "Fired when the extension is first installed, when the extension is updated to a new version, and when **Chrome is updated to a new version**."

Looks likes the origin list is being overwritten with default origin list on every Chrome Browser update.

![image](https://github.com/hoppscotch/hoppscotch-extension/assets/43787455/6eccce63-ef32-4dd6-96c7-241648ce1ca9)

**Comment by SanskritiHarmukh** [comment]
> @liyasthomas @AndrewBastin the bug seems to be triggered when Chrome version update occurs.
> 
> Seems like `chrome.runtime.onInstalled.addListener(()` in src/index.js, Line:358 is using this function which according to the docs is "Fired when the extension is first installed, when the extension is updated to a new version, and when **Chrome is updated to a new version**."
> 
> Looks likes the origin list is being overwritten with default origin list on every Chrome Browser update.
> 
> ![image](https://github.com/hoppscotch/hoppscotch-extension/assets/43787455/6eccce63-ef32-4dd6-96c7-241648ce1ca9)
> 

Hi @tomerr-ma we'll try to reproduce the issue again and revert back to you. Thanks for the update.

**Comment by amk-dev** [comment]
closing as the PR #282 is merged.
