### ISSUE TITLE
 User `postgres` was denied access on the database `postwoman.public`

### ISSUE THREAD

**Issue by pppppino** [hoppscotch/hoppscotch-extension#292]
I'm sure that  user `postgres` has access to postwoman database, but when I start container, it will always appear this error!

**Comment by amk-dev** [comment]
Ideally this should be a config issue. if not you should open an issue at [hoppscotch/hoppscotch](https://github.com/hoppscotch/hoppscotch).

closing this as this is not related to hoppscotch-extension.
